theme = "ananke"
baseURL = 'https://zhuchb.github.io/easthrees-blog'
languageCode = 'en-us'
title = 'Easthrees Studio'
resourceDir = "resources"

[params]
  text_color = ""
  author = "Chuanbo Zhu"
  favicon = ""
  site_logo = ""
  description = "This is a blog for three of us."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  #recent_posts_number = 3